// frontend/src/views/Register.tsx
import {Button, InputLabel, TextField} from "@material-ui/core";
import React, {useState} from "react";
import {Controller, useForm} from "react-hook-form";
import {useServerConfig} from "../utils/ServerConfigProvider";

import '../assets/scss/Register.scss';
import i18n from "i18n-js";
import {ValidationErrors} from "../types/ValidationErrors";

interface IFormInputs {
    Username: string;
    Email: string;
    Password: string;
    Password2: string;
    InviteCode: string;
}

export function Register() {
    const {Config} = useServerConfig();

    const {control, handleSubmit} = useForm<IFormInputs>();
    const [validationErrors, setValidationErrors] = useState<ValidationErrors>();
    const [status, setStatus] = useState<null | 'error' | 'success' | 'pending'>(null);
    const [message, setMessage] = useState<null | String>(null);

    const onSubmit = async (data: IFormInputs) => {
        setStatus('pending');
        const response = await fetch('/api/auth/register', {
            method: 'POST',
            body: JSON.stringify(data),
        });

        if (!response.ok) {
            setStatus('error');
            try {
                const data = await response.json();
                if (data.Violations) {
                    setValidationErrors(data.Violations);
                } else {
                    setMessage(data.Message);
                }
            } catch {
                setMessage("Error occurred");
            }
        } else {
            setStatus('success');

            const result = await response.json();
            setMessage(result.Message);
        }
    }

    return <div className="centeredBlock">
        <h1>{i18n.t('registration.title')}</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
            <InputLabel htmlFor="Username">{i18n.t('registration.username')}</InputLabel>
            <Controller
                name="Username"
                control={control}
                defaultValue=""
                render={({onChange, value}) => <TextField onChange={onChange}
                                                          value={value}
                                                          disabled={status === 'pending'}
                                                          required
                                                          fullWidth/>}
            />

            <InputLabel htmlFor="Email">{i18n.t('registration.email')}</InputLabel>
            <Controller
                name="Email"
                control={control}
                defaultValue=""
                render={({onChange, value}) => <TextField onChange={onChange}
                                                          disabled={status === 'pending'}
                                                          value={value}
                                                          type="email"
                                                          required
                                                          fullWidth/>}
            />

            <InputLabel htmlFor="Password">{i18n.t('registration.password')}</InputLabel>
            <Controller
                name="Password"
                control={control}
                defaultValue=""
                render={({onChange, value}) => <TextField onChange={onChange}
                                                          disabled={status === 'pending'}
                                                          value={value}
                                                          type="password"
                                                          autoComplete="new-password"
                                                          required
                                                          fullWidth/>}
            />

            <InputLabel htmlFor="Password2">{i18n.t('registration.repeatPassword')}</InputLabel>
            <Controller
                name="Password2"
                control={control}
                defaultValue=""
                render={({onChange, value}) => <TextField onChange={onChange}
                                                          disabled={status === 'pending'}
                                                          value={value}
                                                          type="password"
                                                          autoComplete="new-password"
                                                          required
                                                          fullWidth/>}
            />

            {
                !Config.RegistrationAllowed
                &&
                <>
                    <InputLabel htmlFor="inviteCode">{i18n.t('registration.inviteCode')}</InputLabel>
                    <Controller
                        name="InviteCode"
                        control={control}
                        defaultValue=""
                        render={({onChange, value}) => <TextField onChange={onChange}
                                                                  disabled={status === 'pending'}
                                                                  value={value}
                                                                  type="text"
                                                                  autoComplete="new-password"
                                                                  required
                                                                  fullWidth/>}
                    />
                </>
            }

            {
                message !== null
                &&
                <span className={status ?? ''}>{message}</span>
            }

            <Button type="submit" disabled={status === 'pending'}>
                {i18n.t('registration.button')}
            </Button>
        </form>
    </div>;
}

// frontend/src/views/Register.vue
<template>
  <div id="content" class="centeredContent">
    <form @submit.prevent="register" class="centeredBox">
      <CustomInput :violations="violations" id="Username" type="text" label="Username" v-model="username"
                   :required="true"/>

      <CustomInput :violations="violations" id="Email" type="email" label="Email" v-model="email" :required="true"/>

      <CustomInput :violations="violations" id="Password" type="password" label="Password" v-model="password"
                   :required="true"/>

      <CustomInput id="Password2" type="password" label="Repeat password" v-model="password2"
                   :required="true"/>

      <CustomInput :violations="violations" id="InviteCode" type="text" v-if="!RegistrationAllowed"
                   label="Invitation code"
                   :model="inviteCode"
                   :required="true"/>

      <span class="message error" v-if="error.length > 0">{{ error }}</span>

      <CustomSubmit :disabled="status === 'pending'"/>
    </form>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import CustomInput from "@/components/CustomInput.vue";
import CustomSubmit from "@/components/CustomSubmit.vue";
import {mapState} from "vuex";

export default Vue.extend({
  name: 'Register',
  components: {CustomInput, CustomSubmit},
  data() {
    return {
      username: '',
      email: '',
      password: '',
      password2: '',
      inviteCode: '',
      status: 'none',
      error: '',
      violations: [],
    }
  },
  computed: {
    ...mapState({
      RegistrationAllowed: (state: any) => state.Server.RegistrationAllowed,
    })
  },
  methods: {
    register: function () {
      this.status = 'pending';

      this.$http.post("/api/auth/register", {
        Username: this.username,
        Email: this.email,
        Password: this.password,
        InviteCode: this.inviteCode,
      })
          .then(resp => {
            //this.error = resp.data.Message;

            this.username = '';
            this.password = '';
            this.password2 = '';
            this.email = '';

            //this.error = "Succes";
            //this.status = 'success';
          })
          .catch(err => {
            this.status = 'none';
            this.password = '';
            this.password2 = '';

            const data = err.response.data;
            if (data.Message) {
              this.error = err.response.data.Message;
            }

            if (data.Violations) {
              this.violations = data.Violations;
            }
          })
    }
  }
});
</script>

<style lang="scss" scoped>
@import "../assets/CenteredForm.scss";

</style>
